spring:
    mail:
        host: smtp.zoho.com
        password: <YourEmailPassword>
        port: 465
        properties:
            mail:
                smtp:
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory
                        fallback: false
                    ssl:
                        trust: smtp.zoho.com
                    starttls:
                        enable: 'false'
        username: <YourEmail>
